openapi: 3.1.0
info:
  title: Newsletter Context API for CustomGPT
  description: Returns processed newsletter chunks for CustomGPT RAG queries
  version: 1.0.0

servers:
  - url: https://eabc-90-230-169-203.ngrok-free.app
    description: Development server

paths:
  /api/newsletter-context:
    get:
      summary: Get recent newsletter content chunks
      description: Retrieves processed content chunks from newsletters for use in GPT responses
      operationId: GetNewsletterContext
      parameters:
        - name: days
          in: query
          description: Number of past days to search (default is 7)
          required: true
          schema:
            type: integer
            default: 7
            minimum: 1
        - name: query
          in: query
          description: the entire user question to search relevant content for
          required: true
          schema:
            type: string
        - name: maxResults
          in: query
          description: Maximum number of content chunks to return (default 10, max 50)
          required: true
          schema:
            type: integer
            default: 10
            maximum: 50

      responses:
        '200':
          description: Successfully retrieved context chunks
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  chunks:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        content:
                          type: string
                          description: The relevant snippet of the newsletter
                        headline:
                          type: string
                          description: Title or subject of the newsletter
                        author:
                          type: string
                        sourceUrl:
                          type: string
                          format: uri
                        publishedAt:
                          type: string
                          format: date-time
                        tags:
                          type: array
                          items:
                            type: string
        '400':
          description: Bad request
        '404':
          description: Server not found
        '429':
          description: Rate limit exceeded
        '500':
          description: Server error