openapi: 3.1.0
info:
  title: Gmail Newsletter API for CustomGPT
  description: API to fetch Gmail newsletter emails for CustomGPT integration
  version: 1.0.0
servers:
  - url: https://localhost
    description: Development server

paths:
  /api/emails:
    get:
      summary: Get latest newsletter emails
      description: Retrieves the latest newsletter emails from Gmail inbox
      operationId: GetLatestNewsletters
      parameters:
        - name: maxResults
          in: query
          description: Maximum number of emails to return (default 10, max 100)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
        - name: query
          in: query
          description: Gmail search query (e.g., "is:unread", "from:substack.com", "newer_than:7d")
          required: false
          schema:
            type: string
        - name: includeBody
          in: query
          description: Whether to include full email body content
          required: false
          schema:
            type: boolean
            default: false
        - name: markAsRead
          in: query
          description: Whether to mark emails as read after fetching
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  count:
                    type: integer
                  emails:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        threadId:
                          type: string
                        from:
                          type: string
                        fromName:
                          type: string
                        to:
                          type: string
                        subject:
                          type: string
                        snippet:
                          type: string
                        date:
                          type: string
                        timestamp:
                          type: integer
                        newsletterName:
                          type: string
                        articleUrls:
                          type: array
                          items:
                            type: string
                        labels:
                          type: array
                          items:
                            type: string
                        bodyPlain:
                          type: string
                        bodyHtml:
                          type: string
                  timestamp:
                    type: string
                    format: date-time
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '429':
          description: Rate limit exceeded
        '500':
          description: Server error

  /api/newsletters:
    get:
      summary: Get newsletter summary
      description: Get summary of recent newsletters grouped by sender
      operationId: GetNewsLettersSummary
      parameters:
        - name: days
          in: query
          description: Number of days to look back (default 7)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 30
            default: 7
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  count:
                    type: integer
                  newsletters:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        sender:
                          type: string
                        senderName:
                          type: string
                        count:
                          type: integer
                        latestSubject:
                          type: string
                        latestDate:
                          type: string
                        latestTimestamp:
                          type: integer
                  period:
                    type: string
                  timestamp:
                    type: string
                    format: date-time

  /api/search:
    get:
      summary: Search emails
      description: Search emails with custom Gmail query
      operationId: SearchEmails
      parameters:
        - name: q
          in: query
          description: Gmail search query
          required: true
          schema:
            type: string
        - name: maxResults
          in: query
          description: Maximum number of results (default 10, max 50)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 10
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  count:
                    type: integer
                  emails:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        threadId:
                          type: string
                        from:
                          type: string
                        fromName:
                          type: string
                        subject:
                          type: string
                        snippet:
                          type: string
                        date:
                          type: string
                        timestamp:
                          type: integer
                        newsletterName:
                          type: string
                        articleUrls:
                          type: array
                          items:
                            type: string
                        labels:
                          type: array
                          items:
                            type: string
                  query:
                    type: string
                  timestamp:
                    type: string
                    format: date-time

  /api/emails/{messageId}:
    get:
      summary: Get specific email
      description: Retrieves a specific email by its message ID
      operationId: GetEmail
      parameters:
        - name: messageId
          in: path
          required: true
          description: Gmail message ID
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  email:
                    type: object
                    properties:
                      id:
                        type: string
                      threadId:
                        type: string
                      from:
                        type: string
                      to:
                        type: string
                      subject:
                        type: string
                      snippet:
                        type: string
                      date:
                        type: string
                        format: date-time
                      body:
                        type: string
                      labels:
                        type: array
                        items:
                          type: string
                  timestamp:
                    type: string
                    format: date-time

components:
  schemas:
    Pet:
      type: object
      required:
        - name
        - photoUrls
      properties:
        id:
          type: integer
          format: int64
        category:
          $ref: "#/components/schemas/Category"
        name:
          type: string
          example: doggie
        photoUrls:
          type: array
          items:
            type: string
        tags:
          type: array
          items:
            $ref: "#/components/schemas/Tag"
        status:
          type: string
          enum:
            - pending
            - available
            - sold
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
